[template]
src	= "haproxy.cfg"
dest	= "/etc/haproxy/haproxy.cfg"
keys	= [
    "owncloud",
]
reload_cmd 	= "haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -d -D -sf $(cat /var/run/haproxy.pid)"
